'use strict';
const $ = id => document.getElementById(id);
const paths = {
 overview:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',
 apps:'m12 3 9 5-9 5-9-5 9-5Zm-9 9 9 5 9-5M3 16l9 5 9-5',
 chart:'M2 12h4l3-8 5 16 3-8h5',leaf:'M20 3C8 2 2 9 6 16c7 5 15-1 14-13ZM4 21 16 9',
 settings:'M4 6h16M4 12h16M4 18h16M8 3v6M16 9v6M10 15v6',
 cpu:'M6 6h12v12H6zM9 9h6v6H9zM9 2v4M15 2v4M9 18v4M15 18v4M2 9h4M2 15h4M18 9h4M18 15h4',
 memory:'M4 5h16v14H4zM8 9v6M12 9v6M16 9v6',bolt:'m13 2-9 12h7l-1 8L21 9h-8l0-7Z',
 arrow:'M5 12h14m-5-5 5 5-5 5',record:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18Zm0 6a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z',
 terminal:'M3 4h18v16H3zM7 9l3 3-3 3M13 15h4'
};
function icon(name) { const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.classList.add('icon');svg.setAttribute('aria-hidden','true');const p=document.createElementNS(svg.namespaceURI,'path');p.setAttribute('d',paths[name]||paths.terminal);svg.append(p);return svg; }
document.querySelectorAll('[data-icon]').forEach(e=>e.append(icon(e.dataset.icon)));
for(let i=0;i<23;i++){const e=document.createElementNS('http://www.w3.org/2000/svg','ellipse');for(const [k,v] of Object.entries({cx:170,cy:120,rx:164-i*5.2,ry:109-i*3.3,fill:'none',stroke:'#bedbb8','stroke-width':.8,opacity:.16+i*.019}))e.setAttribute(k,v);$('contour-lines').append(e);}
let token=sessionStorage.getItem('seagreen-access')||'';
if(location.hash.length>30){token=location.hash.slice(1);sessionStorage.setItem('seagreen-access',token);history.replaceState(null,'',location.pathname);}
let state=null, records=[], page='overview', powerChart=false, comparisons=new Set(), requestPending=false;
const fmt=(n,d=1)=>n==null||!Number.isFinite(n)?'—':n.toFixed(d);
const size=n=>n>=1024**3?fmt(n/1024**3)+' GB':fmt(n/1024**2)+' MB';
const elapsed=r=>Math.max(0,r.ended-r.started);
const coverage=r=>elapsed(r)>0?Math.min(1,r.coveredSeconds/elapsed(r)):0;
const duration=n=>`${Math.floor(n/60)}m ${Math.floor(n%60)}s`;
function el(tag,text,cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node;}
function notice(message){$('notice').textContent=message||'';$('notice').hidden=!message;}
async function api(path,body,blob=false){const options={headers:{Authorization:'Bearer '+token},cache:'no-store'};if(body!==undefined){options.method='POST';options.headers['Content-Type']='application/json';options.body=JSON.stringify(body);}const response=await fetch('/api/'+path,options);if(!response.ok){let data;try{data=await response.json();}catch{data={error:'Local request failed.'};}throw Error(data.error||'Local request failed.');}return blob?response.blob():response.json();}
async function action(fn){try{notice('');await fn();await refresh();}catch(e){notice(e.message);}}
function go(next){page=next;document.querySelectorAll('.page').forEach(e=>e.hidden=e.id!==page);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('selected',b.dataset.page===page));$('page-title').textContent=page[0].toUpperCase()+page.slice(1);if(page==='experiments')loadRecords().catch(e=>notice(e.message));if(state)render();window.scrollTo({top:0,behavior:'instant'});}
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.page)));
document.querySelectorAll('[data-goto]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.goto)));
document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();go('overview');});
function ask(title,body,label='Confirm'){return new Promise(resolve=>{const d=$('confirm-dialog');$('confirm-title').textContent=title;$('confirm-body').textContent=body;$('confirm-ok').textContent=label;let answer=false;$('confirm-ok').onclick=()=>{answer=true;d.close();};$('confirm-cancel').onclick=()=>d.close();d.onclose=()=>resolve(answer);d.showModal();});}
function openRecord(){if(state?.active){action(async()=>{await api('record/finish',{});await loadRecords();});return;}$('record-dialog').showModal();}
$('record-button').onclick=openRecord;$('new-recording').onclick=openRecord;$('cancel-recording').onclick=()=>$('record-dialog').close();
$('record-form').onsubmit=e=>{e.preventDefault();action(async()=>{await api('record/start',{title:$('record-title').value,notes:$('record-notes').value,units:Number($('record-units').value),unitName:$('record-unit-name').value});$('record-dialog').close();go('experiments');});};
$('finish-recording').onclick=()=>action(async()=>{await api('record/finish',{});await loadRecords();});
$('search').oninput=renderProcesses;$('sort').onchange=renderProcesses;
$('chart-cpu').onclick=()=>{powerChart=false;drawChart();};$('chart-power').onclick=()=>{powerChart=true;drawChart();};
$('pause-monitor').onclick=()=>action(()=>api('monitor/pause',{paused:!state?.paused}));
$('job-form').onsubmit=e=>{e.preventDefault();action(async()=>{const executable=$('executable').value.trim();if(await ask('Launch this executable?',executable+' will run with your user permissions. Arguments are passed directly, without a shell. Only run programs you trust.','Launch job'))await api('job/launch',{executable,arguments:$('arguments').value.split(/\r?\n/).filter(x=>x!==''),efficient:$('efficient').checked});});};
$('stop-job').onclick=()=>action(async()=>{if(await ask('Stop the launched process?','Only the process launched by Seagreen receives the termination request. Independently running child processes may continue.','Request termination'))await api('job/stop',{});});
function renderProcesses(){if(!state?.sample)return;const q=$('search').value.toLowerCase(),sort=$('sort').value;const processes=state.sample.processes.filter(p=>p.name.toLowerCase().includes(q)).sort((a,b)=>(b[sort]??-1)-(a[sort]??-1));const fragment=document.createDocumentFragment();for(const p of processes){const tr=el('tr');const io=p.readRate==null&&p.writeRate==null?'—':fmt(((p.readRate||0)+(p.writeRate||0))/1024,0)+' KB/s';for(const value of [p.name,String(p.pid),size(p.memory),io,fmt(p.cpu)+'%'])tr.append(el('td',value));const actions=el('td'),quit=el('button','Quit','process-action'),force=el('button','Force quit','process-action');quit.onclick=()=>controlProcess(p,'quit');force.onclick=()=>controlProcess(p,'force');quit.setAttribute('aria-label','Quit '+p.name+' PID '+p.pid);force.setAttribute('aria-label','Force quit '+p.name+' PID '+p.pid);quit.disabled=force.disabled=!!p.protected;if(p.protected){quit.title=force.title='Protected system or Seagreen process';}actions.append(quit,force);tr.append(actions);fragment.append(tr);}if(!processes.length){const tr=el('tr'),td=el('td','No matching processes.');td.colSpan=6;tr.append(td);fragment.append(tr);}$('process-rows').replaceChildren(fragment);$('process-note').textContent=`${processes.length} processes shown · ${state.sample.inaccessible} could not be read. Some system processes are protected. Shared memory can appear in multiple processes.`;}
function renderTop(){const fragment=document.createDocumentFragment();for(const p of state.sample.processes.slice(0,4)){const row=el('div',undefined,'process-row'),symbol=el('span',undefined,'process-symbol');symbol.append(icon('terminal'));const info=el('div');info.append(el('strong',p.name),el('small','PID '+p.pid));row.append(symbol,info,el('span',fmt(p.cpu)+'%','value'));fragment.append(row);}$('top-processes').replaceChildren(fragment);}
function render(){if(!state?.sample)return;const s=state.sample;$('connection').replaceChildren(el('i'),document.createTextNode(state.paused?'Monitoring paused':'Local monitoring · every 2 seconds'));$('cpu-value').textContent=fmt(s.cpu);$('memory-value').textContent=fmt(s.memory/1024**3);$('power-value').textContent=fmt(s.power?.watts);$('power-scope').textContent=s.power?.scope||'No supported power reading';$('platform-tag').textContent=s.platform+' · '+s.cores+' logical cores';$('record-button').replaceChildren(icon('record'),document.createTextNode(state.active?'Finish recording':'Record session'));$('active-recording').hidden=!state.active;$('new-recording').disabled=!!state.active;if(state.active){$('active-title').textContent=state.active.title;$('active-stats').textContent=duration(elapsed(state.active))+' · '+fmt(coverage(state.active)*100,0)+'% power coverage · '+state.active.points.length+' samples';}const job=state.job;$('job-name').textContent=job.name||'Ready when you are';$('job-status').textContent=job.status;$('job-policy').textContent=job.policy||'';$('job-output').textContent=job.output;$('job-output').hidden=!job.output;$('stop-job').hidden=!job.running;$('launch-button').disabled=job.running;$('pause-monitor').textContent=state.paused?'Resume monitoring':'Pause monitoring';$('pause-monitor').disabled=!!state.active;$('collection-detail').textContent='Last collection: '+fmt(s.collectionMS)+' ms · sample interval: 2 seconds · live chart: 5 minutes';$('source-name').textContent=s.power?.source||'No live power source';if(s.power)$('source-detail').textContent=s.power.scope+'. Hardware package counters do not include the display, power supply, or other device components.';if(s.cpu>70){$('insight-title').textContent='There’s substantial work in progress.';$('insight-body').textContent='Check which processes are busy. High CPU may be useful work; it does not by itself mean energy is being wasted.';}else{$('insight-title').textContent='Start with a baseline.';$('insight-body').textContent='Record a typical task before changing its settings. Repeat it afterward to compare runtime, resource usage, and available energy data.';}if(page==='overview'){renderTop();drawChart();}if(page==='applications')renderProcesses();if(state.error)notice(state.error);}
function drawChart(){const canvas=$('history-chart');if(page!=='overview'||!state)return;const points=state.history||[];const valid=points.some(p=>(powerChart?p.watts:p.cpu)!=null);$('chart-empty').hidden=valid||!powerChart;$('chart-cpu').classList.toggle('active',!powerChart);$('chart-power').classList.toggle('active',powerChart);$('chart-caption').textContent=powerChart?(state.sample?.power?.source||'No power samples available'):'System utilization, sampled every two seconds';canvas.setAttribute('aria-label',powerChart?'Power history in watts':'System CPU history, percent of all cores');const box=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;if(!box.width)return;canvas.width=box.width*dpr;canvas.height=box.height*dpr;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);const w=box.width,h=box.height,l=35,r=8,t=8,b=25;const maximum=powerChart?Math.max(10,...points.map(p=>(p.watts||0)*1.2)):100;ctx.font='10px -apple-system,Segoe UI,sans-serif';ctx.strokeStyle='#e4e9dc';ctx.fillStyle='#71806e';for(let i=0;i<5;i++){let y=t+(h-t-b)*i/4;ctx.beginPath();ctx.moveTo(l,y);ctx.lineTo(w-r,y);ctx.stroke();ctx.fillText(String(Math.round(maximum*(1-i/4))),0,y+3);}if(!points.length)return;const end=points[points.length-1].date,start=end-300;const x=p=>l+(p.date-start)/300*(w-l-r),y=v=>t+(1-v/maximum)*(h-t-b);ctx.lineWidth=2;ctx.strokeStyle='#397956';ctx.beginPath();let last=null;for(const p of points){const v=powerChart?p.watts:p.cpu;if(v==null){last=null;continue;}if(!last||p.date-last.date>15||(powerChart&&p.powerKey!==last.powerKey))ctx.moveTo(x(p),y(v));else ctx.lineTo(x(p),y(v));last=p;}ctx.stroke();for(let i=0;i<5;i++){const time=start+i*75;ctx.fillText(new Date(time*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),l+i*(w-l-r)/4-13,h-3);}}
async function loadRecords(){records=await api('recordings');const fragment=document.createDocumentFragment();if(!records.length){const empty=el('div',undefined,'empty');empty.append(el('h3','Your first baseline.'),el('p','Record a build, a render, or a local-model workload to begin.'));fragment.append(empty);}for(const r of records){const row=el('div',undefined,'record-row'),check=el('input');check.type='checkbox';check.checked=comparisons.has(r.id);check.setAttribute('aria-label','Compare '+r.title);check.onchange=()=>{if(check.checked){if(comparisons.size>=2)comparisons.clear();comparisons.add(r.id);}else comparisons.delete(r.id);loadRecords().catch(e=>notice(e.message));};const info=el('div',undefined,'record-info');info.append(el('h3',r.title),el('small',new Date(r.started*1000).toLocaleString()+' · '+duration(elapsed(r))+' · '+fmt(coverage(r)*100,0)+'% power coverage'));if(r.notes)info.append(el('p',r.notes,'subtle'));const actions=el('div',undefined,'record-actions');for(const format of ['csv','json']){const b=el('button',format.toUpperCase());b.onclick=()=>action(async()=>{const blob=await api('record/export',{id:r.id,format},true),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='Seagreen-'+r.id+'.'+format;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});actions.append(b);}const remove=el('button','Delete');remove.classList.add('danger');remove.onclick=()=>action(async()=>{if(await ask('Delete this recording?',r.title+' will be permanently removed from local history.','Delete recording')){await api('record/delete',{id:r.id});comparisons.delete(r.id);await loadRecords();}});actions.append(remove);row.append(check,info,actions);fragment.append(row);}$('recordings-list').replaceChildren(fragment);renderComparison();}
function renderComparison(){const selected=records.filter(r=>comparisons.has(r.id)),box=$('comparison');box.hidden=selected.length!==2;if(selected.length!==2)return;const[a,b]=selected;box.replaceChildren(el('h2','Session comparison'),el('h3',b.title+' → '+a.title));let issue;if(a.device!==b.device)issue='Use recordings from the same device.';else if(coverage(a)<.9||coverage(b)<.9)issue='At least 90% power coverage is needed in both recordings.';else if(a.powerKeys.length!==1||JSON.stringify(a.powerKeys)!==JSON.stringify(b.powerKeys))issue='Use matching power sources and measurement scopes.';else if(a.unitName!==b.unitName||!(a.completedUnits>0&&b.completedUnits>0))issue='Use the same completed-work unit for both recordings.';if(issue){box.append(el('p',issue+' Energy savings are not calculated for this pair.'));}else{const av=a.energyWh/a.completedUnits,bv=b.energyWh/b.completedUnits;box.append(el('p',`${fmt(bv,4)} → ${fmt(av,4)} Wh per ${a.unitName}`));box.append(el('h3',bv>0?`${av>=bv?'+':''}${fmt((av-bv)/bv*100)}% observed change`:'No positive baseline energy to compare.'));box.append(el('p','Observed difference, not a causal guarantee. Repeat the same workload and account for background activity.','subtle'));}box.append(el('p','Runtime: '+duration(elapsed(b))+' → '+duration(elapsed(a)),'subtle'));}
async function refresh(){if(requestPending)return;requestPending=true;try{state=await api('state');render();}catch(e){$('connection').textContent='Disconnected';notice(e.message);}finally{requestPending=false;}}
window.addEventListener('resize',drawChart);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});
refresh();setInterval(()=>{if(!document.hidden)refresh();},2000);

function controlProcess(p,mode){action(async()=>{const force=mode==='force';if(await ask((force?'Force quit ':'Quit ')+p.name+'?', 'PID '+p.pid+'. '+(force?'Unsaved work will be lost. Only this process is targeted; child processes may remain.':'Requests that this process close. On Windows, the app may prompt to save. On other systems, SIGTERM is sent. Child processes may remain.'),force?'Force quit':'Request quit')){const result=await api('process/control',{pid:p.pid,created:p.created,mode});notice(result.message);}});}
